# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('os', models.CharField(max_length=50, verbose_name='Device OS')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Model')),
                ('reg_id', models.TextField(blank=True, null=True, unique=True, verbose_name='Registration ID')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='App Version')),
                ('active', models.BooleanField(default=True)),
                ('extra', models.TextField(blank=True, help_text="Stringified dict. Like 'installed app name'", null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('extra', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user', to='geolocation.Device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='room_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='geolocation.RoomUser'),
        ),
    ]
